# Generated by Django 5.0.6 on 2024-12-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
