# Generated by Django 5.1.2 on 2025-01-08 16:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_seat_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reservation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
