# Generated by Django 5.0.6 on 2024-06-16 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adcategory',
            fields=[
                ('catid', models.AutoField(primary_key=True, serialize=False)),
                ('catname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'adcategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('adminid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True, unique=True)),
            ],
            options={
                'db_table': 'administrator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('advertisementid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('creationdate', models.DateTimeField()),
                ('updatedate', models.DateTimeField(blank=True, null=True)),
                ('addesc', models.CharField(blank=True, max_length=511, null=True)),
            ],
            options={
                'db_table': 'advertisement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('pubid', models.AutoField(primary_key=True, serialize=False)),
                ('isactive', models.BooleanField()),
                ('regdate', models.DateTimeField()),
            ],
            options={
                'db_table': 'publisher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Businesscategory',
            fields=[
                ('catid', models.AutoField(primary_key=True, serialize=False)),
                ('catname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'businesscategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('cityid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reportcategory',
            fields=[
                ('catid', models.AutoField(primary_key=True, serialize=False)),
                ('catname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'reportcategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('stateid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Statusstate',
            fields=[
                ('adstateid', models.AutoField(primary_key=True, serialize=False)),
                ('adstatename', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'statusstate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modified',
            fields=[
                ('adminid', models.OneToOneField(db_column='adminid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='WolMain.administrator')),
                ('moddate', models.DateTimeField()),
                ('tostateid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modified',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Adstatus',
            fields=[
                ('advertisementid', models.OneToOneField(db_column='advertisementid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='WolMain.advertisement')),
                ('admincomment', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'adstatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Digitalproduct',
            fields=[
                ('advertisementid', models.OneToOneField(db_column='advertisementid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='WolMain.advertisement')),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'digitalproduct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Homeappliance',
            fields=[
                ('advertisementid', models.OneToOneField(db_column='advertisementid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='WolMain.advertisement')),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('material', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'homeappliance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('advertisementid', models.OneToOneField(db_column='advertisementid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='WolMain.advertisement')),
            ],
            options={
                'db_table': 'other',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Realestate',
            fields=[
                ('advertisementid', models.OneToOneField(db_column='advertisementid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='WolMain.advertisement')),
                ('area', models.IntegerField(blank=True, null=True)),
                ('constructiondate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'realestate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('advertisementid', models.OneToOneField(db_column='advertisementid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='WolMain.advertisement')),
                ('reportid', models.IntegerField()),
                ('rdesc', models.CharField(blank=True, max_length=511, null=True)),
            ],
            options={
                'db_table': 'report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('advertisementid', models.OneToOneField(db_column='advertisementid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='WolMain.advertisement')),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('productionyear', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vehicle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('pubid', models.OneToOneField(db_column='pubid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='WolMain.publisher')),
                ('userid', models.IntegerField(blank=True, null=True)),
                ('bname', models.CharField(max_length=255)),
                ('registrationnum', models.BigIntegerField()),
            ],
            options={
                'db_table': 'business',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Normaluser',
            fields=[
                ('pubid', models.OneToOneField(db_column='pubid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='WolMain.publisher')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True, unique=True)),
            ],
            options={
                'db_table': 'normaluser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('userid', models.OneToOneField(db_column='userid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='WolMain.normaluser')),
            ],
            options={
                'db_table': 'visit',
                'managed': False,
            },
        ),
    ]
