# Generated by Django 5.0.6 on 2024-06-19 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WolMain', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adcategory',
        ),
        migrations.RemoveField(
            model_name='modified',
            name='adminid',
        ),
        migrations.RemoveField(
            model_name='adstatus',
            name='advertisementid',
        ),
        migrations.RemoveField(
            model_name='report',
            name='advertisementid',
        ),
        migrations.RemoveField(
            model_name='digitalproduct',
            name='advertisementid',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='advertisementid',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='advertisementid',
        ),
        migrations.RemoveField(
            model_name='homeappliance',
            name='advertisementid',
        ),
        migrations.RemoveField(
            model_name='other',
            name='advertisementid',
        ),
        migrations.RemoveField(
            model_name='business',
            name='pubid',
        ),
        migrations.DeleteModel(
            name='Businesscategory',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.RemoveField(
            model_name='normaluser',
            name='pubid',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='userid',
        ),
        migrations.DeleteModel(
            name='Reportcategory',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='Statusstate',
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
        migrations.DeleteModel(
            name='Modified',
        ),
        migrations.DeleteModel(
            name='Adstatus',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Digitalproduct',
        ),
        migrations.DeleteModel(
            name='Realestate',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
        migrations.DeleteModel(
            name='Homeappliance',
        ),
        migrations.DeleteModel(
            name='Advertisement',
        ),
        migrations.DeleteModel(
            name='Other',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.DeleteModel(
            name='Normaluser',
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
