# Generated by Django 5.0.6 on 2024-11-19 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CityName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Genre', models.CharField(max_length=50)),
                ('DurationMinutes', models.IntegerField()),
                ('ReleaseDate', models.DateField()),
                ('Rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
            options={
                'db_table': 'Movies',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Action', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProvinceName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Provinces',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleName', models.CharField(max_length=15)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CinemaName', models.CharField(max_length=100)),
                ('Address', models.TextField(blank=True, null=True)),
                ('CityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WolApi.city')),
                ('ProvinceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WolApi.province')),
            ],
            options={
                'db_table': 'Cinemas',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('seat_count', models.PositiveIntegerField()),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='WolApi.cinema')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='ProvinceID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WolApi.province'),
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AuditoriumID', models.IntegerField(unique=True)),
                ('StartTime', models.DateTimeField()),
                ('EndTime', models.DateTimeField()),
                ('Capacity', models.IntegerField()),
                ('CinemaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WolApi.cinema')),
                ('MovieID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WolApi.movie')),
            ],
            options={
                'db_table': 'Screenings',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AuditoriumID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WolApi.screening', to_field='AuditoriumID')),
            ],
            options={
                'db_table': 'Seats',
            },
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showtime', models.DateTimeField()),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WolApi.hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WolApi.movie')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('FamilyName', models.CharField(max_length=20)),
                ('BirthDate', models.DateField()),
                ('PhoneNumber', models.CharField(max_length=15, unique=True)),
                ('Email', models.EmailField(max_length=255, unique=True)),
                ('Password', models.TextField()),
                ('RoleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WolApi.role')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PurchaseDateTime', models.DateTimeField()),
                ('SeatID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WolApi.seat')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WolApi.user')),
            ],
            options={
                'db_table': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('ReviewText', models.TextField(blank=True, null=True)),
                ('ReviewDate', models.DateTimeField()),
                ('MovieID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WolApi.movie')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WolApi.user')),
            ],
            options={
                'db_table': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WolApi.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WolApi.role')),
            ],
            options={
                'db_table': 'RolePermissions',
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
