insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1, 1, 'dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut', '1/8/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (3, 1, 'laoreet ut rhoncus aliquet pulvinar', '2/4/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (5, 1, 'nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac', '5/7/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (7, 1, null, null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (9, 1, 'amet nunc viverra dapibus nulla', '8/31/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (11, 2, 'quis augue luctus tincidunt nulla mollis molestie lorem quisque ut', '4/6/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (13, 1, 'porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis', '8/28/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (15, 1, 'montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem', '7/16/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (17, 0, 'sodales scelerisque mauris sit amet eros suspendisse', '2/19/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (19, 1, 'blandit ultrices enim lorem ipsum', '6/3/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (21, 1, 'sociis natoque penatibus et magnis dis', '8/13/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (23, 1, 'amet diam in magna bibendum imperdiet nullam orci pede venenatis non', '4/2/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (25, 1, null, '3/17/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (27, 0, 'donec semper sapien a libero nam dui proin leo', '2/14/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (29, 2, 'iaculis justo in hac habitasse platea dictumst etiam', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (31, 1, 'cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at', '5/31/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (33, 1, 'non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci', '4/20/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (35, 0, 'vel nisl duis ac nibh fusce lacus', '3/11/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (37, 1, 'lacus at velit vivamus vel nulla eget eros elementum', '7/8/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (39, 1, null, '7/13/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (41, 2, 'sollicitudin vitae consectetuer eget rutrum', '8/11/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (43, 0, 'in porttitor pede justo eu massa', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (45, 0, 'purus sit amet nulla quisque arcu libero rutrum', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (47, 1, 'aenean fermentum donec ut mauris eget massa tempor convallis nulla', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (49, 0, 'dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean', '5/22/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (51, 2, 'donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (53, 0, 'pede justo lacinia eget tincidunt eget tempus', '8/2/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (55, 1, 'augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl', '10/4/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (57, 1, 'integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus', '9/4/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (59, 1, 'nulla suspendisse potenti cras in purus eu magna vulputate luctus cum', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (61, 0, null, '12/14/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (63, 1, 'venenatis tristique fusce congue diam id ornare imperdiet sapien', '8/28/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (65, 0, 'lacus curabitur at ipsum ac tellus semper interdum mauris', '10/28/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (67, 1, 'id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (69, 1, 'amet consectetuer adipiscing elit proin interdum mauris', '4/30/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (71, 1, 'est lacinia nisi venenatis tristique fusce congue diam id ornare', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (73, 0, null, '9/19/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (75, 1, 'lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio', '2/9/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (77, 1, 'id turpis integer aliquet massa id lobortis convallis', '12/24/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (79, 0, 'velit id pretium iaculis diam erat fermentum', '5/15/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (81, 1, 'maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (83, 1, null, '8/27/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (85, 0, 'donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet', '1/29/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (87, 1, 'mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem', '7/17/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (89, 0, 'eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec', '5/24/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (91, 1, null, '4/15/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (93, 1, 'lacus curabitur at ipsum ac tellus semper interdum mauris', '10/11/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (95, 1, 'sollicitudin mi sit amet lobortis sapien sapien', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (97, 0, 'congue eget semper rutrum nulla nunc purus', '11/2/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (99, 1, 'consectetuer adipiscing elit proin risus praesent lectus vestibulum', '10/21/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (101, 1, 'nunc vestibulum ante ipsum primis in', '7/15/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (103, 1, null, '7/27/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (105, 0, null, '1/2/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (107, 1, 'vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (109, 1, 'vel augue vestibulum ante ipsum primis', '2/10/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (111, 0, null, null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (113, 1, 'at feugiat non pretium quis lectus suspendisse potenti in', '7/13/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (115, 2, null, '11/11/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (117, 1, 'eu felis fusce posuere felis sed lacus morbi sem mauris laoreet', '12/10/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (119, 1, null, '12/26/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (121, 1, null, '4/10/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (123, 1, null, '7/25/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (125, 2, 'nam tristique tortor eu pede', '9/22/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (127, 1, null, '3/28/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (129, 0, 'ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse', '7/1/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (131, 1, 'non sodales sed tincidunt eu felis fusce posuere', '9/26/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (133, 1, 'justo in blandit ultrices enim lorem ipsum dolor', '9/28/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (135, 0, 'nam congue risus semper porta volutpat quam pede', '11/1/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (137, 2, null, null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (139, 1, 'in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus', '9/14/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (141, 2, 'dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis', '9/12/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (143, 1, 'nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti', '1/22/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (145, 0, null, '3/24/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (147, 0, null, '6/21/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (149, 1, 'in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus', '8/21/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (151, 0, 'interdum eu tincidunt in leo maecenas pulvinar lobortis', '5/12/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (153, 0, 'porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla', '5/7/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (155, 1, null, '2/5/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (157, 0, 'pede ac diam cras pellentesque volutpat dui maecenas tristique est et', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (159, 1, 'tortor duis mattis egestas metus', '11/20/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (161, 0, 'ipsum integer a nibh in', '9/12/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (163, 1, 'porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor', '9/1/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (165, 1, 'sed accumsan felis ut at dolor quis odio consequat varius', '4/3/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (167, 1, null, null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (169, 1, null, '9/27/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (171, 2, null, '10/3/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (173, 1, 'vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia', '9/12/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (175, 1, 'in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna', '3/20/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (177, 0, null, '11/25/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (179, 1, 'faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (181, 1, null, null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (183, 1, 'fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (185, 2, 'nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper', '9/25/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (187, 1, null, null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (189, 2, 'blandit non interdum in ante vestibulum ante ipsum primis in faucibus', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (191, 0, 'arcu adipiscing molestie hendrerit at vulputate', '1/15/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (193, 0, null, '4/13/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (195, 1, 'morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate', '6/29/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (197, 1, null, '7/29/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (199, 0, 'porttitor lorem id ligula suspendisse', '6/14/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (201, 0, 'rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean', '3/8/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (203, 0, null, null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (205, 0, null, '6/17/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (207, 1, null, '9/3/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (209, 1, 'pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea', '2/23/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (211, 0, 'sit amet consectetuer adipiscing elit proin interdum mauris non', '10/15/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (213, 0, 'accumsan tortor quis turpis sed ante vivamus tortor', '7/10/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (215, 0, 'nulla ac enim in tempor', '3/20/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (217, 0, null, '9/24/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (219, 1, 'morbi vel lectus in quam fringilla', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (221, 1, 'tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante', '6/27/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (223, 1, 'sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (225, 1, 'proin leo odio porttitor id consequat in consequat', '8/20/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (227, 0, 'lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (229, 2, 'mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (231, 1, 'quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante', '4/1/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (233, 1, 'vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit', '3/18/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (235, 1, 'pede morbi porttitor lorem id ligula suspendisse ornare consequat', '5/28/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (237, 0, 'rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id', '11/21/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (239, 1, 'nulla neque libero convallis eget eleifend luctus ultricies', '12/24/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (241, 0, 'ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam', '7/4/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (243, 1, 'interdum eu tincidunt in leo maecenas', '5/23/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (245, 0, 'in imperdiet et commodo vulputate justo in', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (247, 1, 'eu nibh quisque id justo sit amet sapien', '3/28/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (249, 0, null, '4/19/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (251, 1, 'augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse', '7/2/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (253, 1, 'justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna', '11/27/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (255, 1, 'dis parturient montes nascetur ridiculus', '11/29/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (257, 2, 'lorem id ligula suspendisse ornare consequat lectus', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (259, 0, 'consequat nulla nisl nunc nisl duis bibendum felis sed interdum', '12/5/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (261, 2, 'convallis nulla neque libero convallis eget', '7/15/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (263, 1, 'justo morbi ut odio cras mi', '3/13/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (265, 1, null, '6/26/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (267, 0, 'in blandit ultrices enim lorem ipsum dolor sit amet consectetuer', '8/27/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (269, 2, 'at turpis donec posuere metus vitae ipsum aliquam non mauris morbi', '1/17/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (271, 0, 'et ultrices posuere cubilia curae duis', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (273, 1, null, '5/8/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (275, 1, 'ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed', '3/10/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (277, 1, 'et magnis dis parturient montes nascetur ridiculus mus etiam', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (279, 1, 'vel est donec odio justo sollicitudin ut suscipit a feugiat et eros', '8/26/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (281, 0, 'justo eu massa donec dapibus duis at velit eu', '9/30/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (283, 1, null, '7/26/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (285, 1, null, '2/23/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (287, 0, 'curae donec pharetra magna vestibulum', '3/5/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (289, 1, null, '8/3/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (291, 0, 'duis ac nibh fusce lacus purus aliquet at', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (293, 0, 'curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat', '4/10/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (295, 1, 'nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac', '10/23/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (297, 1, 'magna at nunc commodo placerat praesent blandit nam nulla integer pede', '1/31/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (299, 1, 'dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (301, 2, 'vulputate vitae nisl aenean lectus', '6/9/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (303, 1, 'aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem', '8/8/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (305, 0, 'purus phasellus in felis donec semper sapien a', '5/9/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (307, 1, 'posuere felis sed lacus morbi sem mauris laoreet ut rhoncus', '10/2/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (309, 1, 'justo eu massa donec dapibus duis at velit eu est congue elementum in hac', '5/23/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (311, 2, null, '12/29/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (313, 0, null, null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (315, 0, 'ante ipsum primis in faucibus orci luctus et', '7/18/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (317, 2, null, '2/19/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (319, 1, 'erat quisque erat eros viverra eget congue eget semper rutrum', '4/12/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (321, 1, 'mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing', '1/29/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (323, 0, 'ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum', '6/10/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (325, 1, null, '1/2/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (327, 2, 'leo pellentesque ultrices mattis odio donec', '10/6/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (329, 1, 'in faucibus orci luctus et', '2/23/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (331, 0, null, '7/26/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (333, 1, null, '5/16/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (335, 0, 'ut suscipit a feugiat et', '9/19/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (337, 0, null, '9/23/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (339, 1, 'fermentum donec ut mauris eget massa tempor convallis', '11/18/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (341, 0, 'ut nulla sed accumsan felis ut', '5/3/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (343, 1, null, '6/4/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (345, 1, 'sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (347, 0, 'ac leo pellentesque ultrices mattis odio donec', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (349, 0, 'blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla', '4/17/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (351, 1, 'id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (353, 1, 'felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed', '4/11/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (355, 1, 'purus eu magna vulputate luctus cum', '9/21/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (357, 0, 'massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (359, 0, 'curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel', '7/1/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (361, 0, null, null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (363, 0, 'nulla sed accumsan felis ut at', '2/26/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (365, 1, 'duis faucibus accumsan odio curabitur', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (367, 1, 'dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum', '11/16/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (369, 2, 'quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent', '1/17/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (371, 1, null, null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (373, 2, 'orci eget orci vehicula condimentum curabitur', '8/9/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (375, 2, null, '4/4/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (377, 1, null, '8/3/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (379, 0, 'ullamcorper purus sit amet nulla', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (381, 2, 'consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat', '8/1/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (383, 1, 'in felis eu sapien cursus vestibulum proin', '7/25/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (385, 1, 'iaculis diam erat fermentum justo nec condimentum neque', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (387, 0, 'lectus vestibulum quam sapien varius ut', '9/12/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (389, 1, 'ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna', '10/23/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (391, 0, 'sed vel enim sit amet nunc viverra dapibus nulla suscipit', '11/4/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (393, 1, 'non interdum in ante vestibulum ante ipsum primis in', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (395, 1, 'dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit', '2/5/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (397, 1, 'etiam faucibus cursus urna ut tellus nulla ut erat', '1/7/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (399, 1, 'non interdum in ante vestibulum ante ipsum primis in', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (401, 2, 'ut erat id mauris vulputate elementum nullam', '2/16/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (403, 1, 'vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean', '4/26/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (405, 1, 'libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (407, 1, 'nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti', '5/3/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (409, 1, 'ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut', '8/21/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (411, 1, 'quis orci eget orci vehicula condimentum curabitur in libero ut', '5/11/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (413, 1, null, '11/25/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (415, 0, 'luctus cum sociis natoque penatibus et magnis', '3/23/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (417, 1, 'elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis', '2/2/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (419, 0, 'pretium nisl ut volutpat sapien arcu sed augue aliquam', '9/17/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (421, 1, 'nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed', '2/13/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (423, 1, 'ac leo pellentesque ultrices mattis odio donec vitae', '2/19/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (425, 1, 'vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id', '3/14/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (427, 0, 'sit amet consectetuer adipiscing elit proin interdum mauris non ligula', '3/21/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (429, 2, 'sapien arcu sed augue aliquam erat volutpat in congue etiam justo', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (431, 2, 'quam pede lobortis ligula sit amet eleifend pede libero quis orci', '6/19/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (433, 1, 'cursus id turpis integer aliquet massa', '6/24/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (435, 2, null, null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (437, 0, 'aliquam erat volutpat in congue etiam justo etiam', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (439, 1, null, '5/18/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (441, 1, 'dui vel sem sed sagittis nam congue risus', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (443, 0, 'in tempus sit amet sem fusce consequat', '11/14/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (445, 1, 'ante ipsum primis in faucibus orci', '11/19/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (447, 1, 'faucibus accumsan odio curabitur convallis', '11/22/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (449, 0, 'odio justo sollicitudin ut suscipit a feugiat et eros vestibulum', '3/5/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (451, 1, 'ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non', '12/4/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (453, 1, null, '7/28/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (455, 0, null, null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (457, 1, 'accumsan tellus nisi eu orci mauris lacinia sapien quis libero', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (459, 1, 'id massa id nisl venenatis lacinia aenean sit amet justo morbi', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (461, 1, 'interdum mauris ullamcorper purus sit amet nulla quisque', '12/1/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (463, 2, 'a suscipit nulla elit ac nulla sed vel enim', '11/26/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (465, 0, 'tristique in tempus sit amet sem fusce consequat nulla', '12/8/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (467, 1, 'in magna bibendum imperdiet nullam orci', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (469, 0, 'eget orci vehicula condimentum curabitur in libero', '5/4/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (471, 2, 'proin leo odio porttitor id consequat in consequat ut nulla', '10/4/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (473, 1, 'platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at', '1/8/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (475, 1, 'in tempor turpis nec euismod scelerisque quam turpis', '9/1/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (477, 1, 'ipsum primis in faucibus orci luctus', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (479, 1, 'congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (481, 1, 'tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat', '6/1/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (483, 1, 'lacus morbi quis tortor id nulla ultrices aliquet maecenas', '12/21/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (485, 1, null, '9/25/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (487, 0, 'justo aliquam quis turpis eget elit sodales', '11/18/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (489, 2, 'in tempor turpis nec euismod scelerisque', '4/3/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (491, 0, null, '2/25/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (493, 2, 'massa id nisl venenatis lacinia aenean sit', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (495, 2, null, '3/30/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (497, 1, 'dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec', '1/11/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (499, 1, 'congue eget semper rutrum nulla nunc', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (501, 0, 'erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis', '4/26/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (503, 0, 'volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim', '12/17/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (505, 0, 'at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (507, 1, 'risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (509, 1, 'hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci', '6/28/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (511, 1, null, '11/30/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (513, 1, 'nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros', '5/10/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (515, 1, 'odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar', '10/9/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (517, 2, null, '1/14/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (519, 2, 'curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (521, 0, null, '3/14/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (523, 0, 'eros vestibulum ac est lacinia nisi venenatis tristique fusce congue', '1/12/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (525, 0, 'in consequat ut nulla sed accumsan', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (527, 0, 'massa tempor convallis nulla neque libero convallis eget eleifend', '9/3/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (529, 1, null, '12/22/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (531, 0, null, null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (533, 0, 'ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus', '6/28/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (535, 1, 'consequat lectus in est risus auctor sed tristique in', '7/29/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (537, 1, 'cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (539, 0, 'nisi vulputate nonummy maecenas tincidunt lacus at', '7/14/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (541, 0, 'morbi a ipsum integer a nibh in quis', '8/19/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (543, 1, 'nulla sed accumsan felis ut at dolor quis odio consequat varius', '4/10/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (545, 0, 'primis in faucibus orci luctus', '12/3/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (547, 1, 'eget elit sodales scelerisque mauris sit amet', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (549, 1, 'aliquet pulvinar sed nisl nunc rhoncus dui vel', '5/19/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (551, 0, 'amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque', '3/23/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (553, 1, 'vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor', '5/2/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (555, 1, 'lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in', '10/15/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (557, 1, 'faucibus orci luctus et ultrices posuere', '5/3/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (559, 2, 'diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (561, 1, null, '10/31/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (563, 1, 'sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue', '9/21/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (565, 1, 'aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo', '10/29/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (567, 1, 'fusce congue diam id ornare imperdiet sapien urna', '8/4/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (569, 0, 'luctus nec molestie sed justo pellentesque viverra', '12/30/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (571, 1, 'pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat', '2/8/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (573, 1, null, '6/13/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (575, 1, null, null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (577, 2, 'sed accumsan felis ut at dolor quis odio consequat varius integer ac leo', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (579, 1, null, '12/8/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (581, 1, 'mauris non ligula pellentesque ultrices phasellus', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (583, 1, 'hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget', '8/15/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (585, 1, 'congue risus semper porta volutpat quam', '9/12/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (587, 0, 'eget rutrum at lorem integer tincidunt ante', '12/9/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (589, 1, null, null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (591, 1, 'pede venenatis non sodales sed tincidunt eu', '7/29/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (593, 1, 'vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae', '10/2/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (595, 0, 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (597, 0, 'luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam', '3/20/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (599, 1, 'consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (601, 0, null, '6/29/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (603, 2, null, '3/1/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (605, 1, 'vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (607, 1, null, '9/5/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (609, 1, 'habitasse platea dictumst morbi vestibulum velit id', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (611, 1, 'platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt', '12/26/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (613, 1, null, '12/1/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (615, 1, null, '11/4/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (617, 0, 'sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (619, 1, 'blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum', '9/5/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (621, 0, 'platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (623, 1, 'sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit', '4/2/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (625, 0, 'ligula sit amet eleifend pede libero quis orci', '5/21/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (627, 0, 'sem fusce consequat nulla nisl nunc nisl duis bibendum felis', '12/1/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (629, 1, 'vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum', '12/7/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (631, 1, 'morbi odio odio elementum eu interdum eu tincidunt in leo', '2/21/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (633, 1, 'non interdum in ante vestibulum ante ipsum primis in faucibus orci', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (635, 1, 'non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac', '11/25/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (637, 0, 'pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique', '12/19/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (639, 1, 'tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh', '3/19/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (641, 0, 'nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed', '3/21/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (643, 0, 'duis aliquam convallis nunc proin at turpis a pede posuere nonummy', '2/6/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (645, 0, 'nulla sed accumsan felis ut at dolor', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (647, 1, null, null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (649, 0, null, '1/30/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (651, 0, 'metus aenean fermentum donec ut mauris eget', '4/2/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (653, 0, null, '2/12/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (655, 0, 'in consequat ut nulla sed accumsan', '6/26/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (657, 1, 'lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus', '9/4/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (659, 1, 'venenatis turpis enim blandit mi in porttitor pede justo', '3/29/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (661, 2, 'vel sem sed sagittis nam', '6/16/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (663, 2, null, '5/17/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (665, 0, 'nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum', '8/28/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (667, 1, 'sociis natoque penatibus et magnis dis parturient', '9/12/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (669, 1, 'vestibulum ante ipsum primis in', '3/21/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (671, 0, null, '11/1/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (673, 0, null, '8/27/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (675, 1, 'pede ullamcorper augue a suscipit nulla', '12/21/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (677, 2, 'tortor risus dapibus augue vel', '9/9/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (679, 1, 'enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin', '8/21/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (681, 0, 'quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo', '7/24/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (683, 1, 'tincidunt lacus at velit vivamus vel nulla eget eros elementum', '3/30/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (685, 1, 'justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis', '3/30/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (687, 2, 'scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec', '10/3/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (689, 1, 'praesent blandit nam nulla integer pede justo lacinia eget', '1/12/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (691, 1, 'odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla', '5/27/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (693, 0, 'purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient', '11/24/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (695, 1, 'aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit', '6/22/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (697, 0, 'ipsum primis in faucibus orci luctus et ultrices posuere', '12/28/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (699, 1, 'natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum', '9/6/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (701, 0, 'amet lobortis sapien sapien non mi integer ac neque duis bibendum', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (703, 0, 'suspendisse potenti in eleifend quam a', '7/10/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (705, 0, 'curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (707, 1, 'tempor convallis nulla neque libero convallis eget eleifend', '4/1/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (709, 0, null, null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (711, 1, 'congue vivamus metus arcu adipiscing molestie hendrerit at', '4/3/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (713, 1, null, '4/9/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (715, 0, 'leo maecenas pulvinar lobortis est phasellus sit amet erat', '12/17/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (717, 2, 'quis orci eget orci vehicula condimentum', '3/10/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (719, 1, null, '9/30/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (721, 0, 'semper est quam pharetra magna ac consequat', '11/19/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (723, 1, 'felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar', '9/28/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (725, 1, 'amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (727, 0, 'interdum in ante vestibulum ante ipsum primis in faucibus', '2/18/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (729, 0, 'pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus', '8/31/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (731, 1, 'justo lacinia eget tincidunt eget tempus vel pede morbi porttitor', '6/9/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (733, 1, 'cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim', '2/6/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (735, 1, 'nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate', '2/10/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (737, 0, null, '10/29/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (739, 0, 'proin leo odio porttitor id consequat', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (741, 0, 'eu orci mauris lacinia sapien quis libero nullam sit', '10/9/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (743, 1, 'tellus nisi eu orci mauris lacinia sapien quis libero nullam', '4/5/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (745, 1, 'porttitor pede justo eu massa donec dapibus duis at velit', '10/26/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (747, 0, null, null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (749, 1, null, '5/9/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (751, 1, 'vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare', '12/9/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (753, 0, 'et tempus semper est quam pharetra magna ac', '4/9/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (755, 1, null, '8/1/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (757, 0, 'pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (759, 1, 'elementum nullam varius nulla facilisi cras', '3/17/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (761, 0, 'mauris ullamcorper purus sit amet nulla quisque arcu', '12/30/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (763, 0, 'tempus vel pede morbi porttitor', '9/2/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (765, 0, 'bibendum morbi non quam nec dui luctus rutrum nulla tellus in', '4/23/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (767, 0, 'eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget', '12/28/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (769, 0, 'auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc', '12/1/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (771, 1, 'arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium', '9/17/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (773, 0, 'quis lectus suspendisse potenti in eleifend quam a odio', '7/17/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (775, 0, 'non interdum in ante vestibulum ante', '7/23/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (777, 0, 'purus phasellus in felis donec semper sapien a libero nam', '6/2/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (779, 0, 'consequat ut nulla sed accumsan', '3/1/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (781, 0, 'orci nullam molestie nibh in lectus', '9/26/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (783, 0, 'donec ut dolor morbi vel lectus', '1/16/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (785, 2, 'id sapien in sapien iaculis', '11/10/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (787, 0, 'fusce congue diam id ornare imperdiet sapien', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (789, 1, 'congue eget semper rutrum nulla nunc purus', '4/19/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (791, 0, 'at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum', '2/29/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (793, 2, 'ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', '2/19/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (795, 1, 'nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi', '1/22/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (797, 0, 'luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam', '5/7/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (799, 0, 'vestibulum sit amet cursus id turpis', '2/13/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (801, 1, 'sapien sapien non mi integer', '3/18/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (803, 0, 'sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet', '9/4/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (805, 0, 'non sodales sed tincidunt eu felis fusce', '8/3/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (807, 1, 'odio consequat varius integer ac leo pellentesque ultrices mattis', '11/13/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (809, 1, 'sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl', '2/8/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (811, 0, 'pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non', '1/15/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (813, 0, 'risus dapibus augue vel accumsan tellus nisi eu', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (815, 0, 'nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam', '10/19/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (817, 1, 'accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (819, 1, null, '3/31/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (821, 1, 'rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin', '12/18/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (823, 1, null, null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (825, 1, 'fusce consequat nulla nisl nunc nisl', '6/2/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (827, 0, 'tempor convallis nulla neque libero convallis eget eleifend', '10/23/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (829, 2, 'lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id', '1/30/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (831, 1, null, '8/25/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (833, 0, null, '11/3/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (835, 1, 'donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam', '2/10/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (837, 0, null, null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (839, 0, 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor', '6/8/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (841, 2, 'curabitur at ipsum ac tellus semper interdum mauris ullamcorper', '2/23/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (843, 1, 'platea dictumst maecenas ut massa quis augue', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (845, 0, 'cursus id turpis integer aliquet massa id lobortis convallis', '4/11/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (847, 1, 'sapien arcu sed augue aliquam erat volutpat in congue etiam', '3/15/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (849, 0, 'mauris laoreet ut rhoncus aliquet', '10/28/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (851, 0, 'nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque', '11/8/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (853, 0, 'in libero ut massa volutpat', '11/8/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (855, 1, 'curae donec pharetra magna vestibulum aliquet ultrices erat', '12/4/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (857, 1, 'bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede', '8/19/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (859, 1, 'eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus', '4/11/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (861, 1, 'in hac habitasse platea dictumst etiam faucibus cursus urna', '5/6/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (863, 0, 'varius nulla facilisi cras non velit nec nisi', '5/14/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (865, 0, null, null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (867, 1, 'varius ut blandit non interdum in', '6/22/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (869, 0, null, '6/7/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (871, 0, 'cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at', '7/15/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (873, 0, 'arcu sed augue aliquam erat', '10/12/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (875, 0, 'pellentesque ultrices phasellus id sapien in sapien', '10/7/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (877, 1, 'semper sapien a libero nam', '6/27/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (879, 2, 'quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (881, 0, 'primis in faucibus orci luctus et ultrices posuere', '5/4/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (883, 0, 'vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt', '4/20/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (885, 0, 'in sagittis dui vel nisl duis ac nibh', '7/30/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (887, 0, 'venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat', '6/6/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (889, 1, 'lacinia sapien quis libero nullam', '1/19/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (891, 0, 'rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis', '3/12/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (893, 0, 'neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis', '2/26/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (895, 0, 'felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa', '3/29/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (897, 2, 'in felis eu sapien cursus vestibulum', '10/19/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (899, 1, 'donec pharetra magna vestibulum aliquet ultrices erat tortor', '2/17/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (901, 0, 'in ante vestibulum ante ipsum primis in', '4/12/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (903, 0, 'maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet', '1/10/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (905, 1, null, '11/22/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (907, 1, 'integer pede justo lacinia eget tincidunt eget', '11/17/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (909, 0, 'mauris viverra diam vitae quam suspendisse potenti nullam', '3/21/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (911, 0, 'nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing', '7/27/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (913, 2, 'dolor sit amet consectetuer adipiscing elit proin risus praesent', '11/7/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (915, 1, 'in tempus sit amet sem fusce consequat nulla', '11/7/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (917, 0, null, '9/19/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (919, 2, null, '5/10/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (921, 2, 'diam in magna bibendum imperdiet', '2/15/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (923, 2, 'sapien cursus vestibulum proin eu mi nulla ac enim', '4/16/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (925, 0, 'risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in', '6/24/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (927, 0, 'odio elementum eu interdum eu tincidunt in leo maecenas', '6/4/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (929, 0, 'nullam orci pede venenatis non sodales sed tincidunt', '10/25/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (931, 0, 'ipsum dolor sit amet consectetuer adipiscing', '3/17/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (933, 1, 'eget orci vehicula condimentum curabitur in libero', '12/25/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (935, 0, 'adipiscing elit proin risus praesent lectus vestibulum quam sapien', '1/11/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (937, 1, 'ipsum dolor sit amet consectetuer adipiscing elit proin risus praesent lectus', '4/30/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (939, 0, 'in magna bibendum imperdiet nullam orci pede venenatis non', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (941, 2, 'diam in magna bibendum imperdiet', '6/18/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (943, 1, null, null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (945, 0, 'ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (947, 1, 'in purus eu magna vulputate luctus cum sociis', '2/5/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (949, 1, 'nunc nisl duis bibendum felis sed interdum venenatis turpis enim', '8/12/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (951, 0, 'at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat', '5/3/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (953, 0, 'primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio', '4/9/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (955, 2, 'orci eget orci vehicula condimentum curabitur in libero ut', '2/21/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (957, 0, 'nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus', '1/4/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (959, 0, 'tempus sit amet sem fusce consequat nulla nisl nunc nisl duis', '1/27/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (961, 0, 'nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit', '4/5/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (963, 1, null, '3/28/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (965, 0, 'in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus', '9/10/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (967, 0, 'bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (969, 1, 'potenti in eleifend quam a odio in', '1/11/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (971, 1, null, '3/31/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (973, 0, null, '12/18/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (975, 0, null, '4/9/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (977, 1, 'diam vitae quam suspendisse potenti', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (979, 2, null, '10/3/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (981, 1, 'sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis', '12/4/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (983, 0, 'viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper', '8/25/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (985, 1, 'in faucibus orci luctus et ultrices posuere cubilia curae', '8/29/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (987, 1, null, '10/4/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (989, 1, 'hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer', '7/9/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (991, 1, null, '11/9/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (993, 1, null, '10/18/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (995, 0, 'lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (997, 1, 'congue eget semper rutrum nulla nunc purus phasellus in felis', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (999, 0, 'id pretium iaculis diam erat fermentum justo nec condimentum neque sapien', '3/18/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1001, 1, 'vestibulum proin eu mi nulla ac enim', '10/1/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1003, 0, 'amet eros suspendisse accumsan tortor quis turpis sed', '10/4/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1005, 2, 'lectus pellentesque eget nunc donec', '8/19/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1007, 1, 'dictumst aliquam augue quam sollicitudin', '7/8/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1009, 0, 'orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed', '3/8/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1011, 1, 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec', '7/4/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1013, 1, null, null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1015, 0, 'hac habitasse platea dictumst etiam faucibus cursus', '6/18/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1017, 0, 'tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean', '9/22/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1019, 0, 'gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer', '12/25/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1021, 1, 'augue luctus tincidunt nulla mollis molestie', '9/26/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1023, 1, 'erat vestibulum sed magna at nunc', '9/24/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1025, 1, 'molestie lorem quisque ut erat curabitur', '11/10/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1027, 1, 'in consequat ut nulla sed', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1029, 0, 'augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1031, 1, null, '8/16/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1033, 0, 'eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas', '12/13/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1035, 1, 'orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti', '7/11/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1037, 1, 'ligula vehicula consequat morbi a ipsum integer a', '11/30/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1039, 1, 'luctus et ultrices posuere cubilia curae donec', '7/22/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1041, 1, 'amet justo morbi ut odio cras mi pede malesuada in imperdiet', '6/29/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1043, 2, 'feugiat non pretium quis lectus', '1/1/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1045, 0, 'in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at', '12/29/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1047, 2, 'non velit donec diam neque vestibulum eget vulputate ut', '5/18/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1049, 1, 'semper rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam', '5/27/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1051, 2, 'diam cras pellentesque volutpat dui maecenas tristique est', '10/19/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1053, 1, 'lectus vestibulum quam sapien varius ut blandit non interdum', '2/24/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1055, 0, null, '2/19/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1057, 0, 'dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1059, 0, 'id massa id nisl venenatis lacinia aenean sit amet justo', '4/21/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1061, 1, 'massa quis augue luctus tincidunt', '5/6/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1063, 1, 'nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue', '6/18/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1065, 1, 'amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque', '4/29/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1067, 0, 'sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus', '6/20/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1069, 1, 'non velit nec nisi vulputate nonummy', '12/5/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1071, 2, 'nulla sed accumsan felis ut at', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1073, 1, null, null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1075, 1, 'auctor gravida sem praesent id', '10/4/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1077, 2, 'integer ac neque duis bibendum morbi non quam nec', '3/23/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1079, 0, null, '9/21/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1081, 0, 'donec semper sapien a libero nam', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1083, 1, 'ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla', '3/22/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1085, 1, 'ultrices vel augue vestibulum ante ipsum primis', '11/18/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1087, 1, 'metus vitae ipsum aliquam non', '10/24/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1089, 0, 'lorem quisque ut erat curabitur gravida nisi at nibh', '5/27/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1091, 0, 'convallis nunc proin at turpis a pede posuere nonummy', '2/27/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1093, 1, null, '11/28/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1095, 2, 'cubilia curae duis faucibus accumsan odio', '2/7/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1097, 0, 'natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum', '2/28/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1099, 0, null, '8/4/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1101, 0, 'faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum', '10/8/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1103, 1, 'nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique', '8/27/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1105, 1, 'penatibus et magnis dis parturient montes', '9/24/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1107, 2, 'vestibulum rutrum rutrum neque aenean auctor gravida sem praesent', '9/1/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1109, 0, 'orci pede venenatis non sodales sed tincidunt eu felis fusce posuere', '10/7/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1111, 1, 'proin eu mi nulla ac enim in tempor turpis nec', '1/8/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1113, 1, 'ut nulla sed accumsan felis ut at dolor', '10/7/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1115, 2, 'lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede', '9/20/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1117, 0, null, '9/26/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1119, 1, 'quisque ut erat curabitur gravida nisi', '1/26/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1121, 1, null, '6/23/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1123, 1, 'lectus vestibulum quam sapien varius ut blandit non interdum', '6/19/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1125, 0, 'ultrices libero non mattis pulvinar nulla pede', '2/22/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1127, 1, 'dui vel sem sed sagittis nam congue risus', '7/15/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1129, 0, 'habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat', '10/29/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1131, 2, 'pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo', '9/17/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1133, 0, null, null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1135, 2, 'felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl', '5/23/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1137, 0, null, null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1139, 0, 'platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec', '4/28/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1141, 0, null, '2/19/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1143, 1, 'sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi', '10/17/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1145, 0, null, '7/21/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1147, 1, 'odio cras mi pede malesuada in imperdiet et commodo vulputate', '11/8/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1149, 2, null, '2/21/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1151, 1, null, '5/30/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1153, 0, 'pulvinar nulla pede ullamcorper augue a suscipit nulla elit', '3/31/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1155, 1, 'diam cras pellentesque volutpat dui maecenas tristique est', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1157, 0, 'auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl', '6/4/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1159, 2, 'integer non velit donec diam neque vestibulum', '12/3/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1161, 0, 'commodo vulputate justo in blandit ultrices', '3/8/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1163, 1, 'sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat', '6/14/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1165, 0, 'primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam', '5/3/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1167, 2, 'interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus', '5/22/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1169, 0, 'consequat lectus in est risus auctor sed tristique in', '11/13/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1171, 0, null, '12/1/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1173, 0, 'sagittis dui vel nisl duis ac', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1175, 1, 'vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus', '6/27/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1177, 0, null, '1/23/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1179, 0, 'vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim', '11/11/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1181, 1, null, null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1183, 0, 'quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi', '6/1/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1185, 0, 'morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus', '2/4/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1187, 1, 'est quam pharetra magna ac consequat metus sapien ut', '2/21/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1189, 0, 'libero rutrum ac lobortis vel dapibus at diam nam tristique', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1191, 0, 'vestibulum ante ipsum primis in faucibus orci luctus et', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1193, 0, 'orci eget orci vehicula condimentum curabitur in libero ut', null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1195, 1, 'quis tortor id nulla ultrices aliquet maecenas leo', '6/14/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1197, 0, 'bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce', '10/4/2023');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1199, 2, 'aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum', '1/21/2024');
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1206, 2, null, null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1207, 2, null, null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1208, 2, null, null);
insert into AdStatus (AdvertisementID, AdStateID, AdminComment, UpdatedAt) values (1209, 2, null, null);

