insert into City (CityID, CName, StateID) values (1, 'Bieqiao', 8);
insert into City (CityID, CName, StateID) values (2, 'Oslo', 7);
insert into City (CityID, CName, StateID) values (3, 'Satipo', 6);
insert into City (CityID, CName, StateID) values (4, 'Sadahayu', 10);
insert into City (CityID, CName, StateID) values (5, 'Gelin', 10);
insert into City (CityID, CName, StateID) values (6, 'Banyubang', 14);
insert into City (CityID, CName, StateID) values (7, 'Hedong', 15);
insert into City (CityID, CName, StateID) values (8, 'Bani Khaddash', 6);
insert into City (CityID, CName, StateID) values (9, 'Saitama', 4);
insert into City (CityID, CName, StateID) values (10, 'Ugep', 9);
insert into City (CityID, CName, StateID) values (11, 'Gachala', 15);
insert into City (CityID, CName, StateID) values (12, 'Chojnice', 2);
insert into City (CityID, CName, StateID) values (13, 'Fengcheng', 4);
insert into City (CityID, CName, StateID) values (14, 'Al Yarubiyah', 2);
insert into City (CityID, CName, StateID) values (15, 'Bakow', 2);
insert into City (CityID, CName, StateID) values (16, 'Khryashchevka', 6);
insert into City (CityID, CName, StateID) values (17, 'Goteborg', 6);
insert into City (CityID, CName, StateID) values (18, 'Muravlenko', 9);
insert into City (CityID, CName, StateID) values (19, 'Bodo', 1);
insert into City (CityID, CName, StateID) values (20, 'Hrodna', 15);
insert into City (CityID, CName, StateID) values (21, 'Chalon-sur-Saône', 4);
insert into City (CityID, CName, StateID) values (22, 'Famenin', 3);
insert into City (CityID, CName, StateID) values (23, 'Khujirt', 7);
insert into City (CityID, CName, StateID) values (24, 'Las Americas', 4);
insert into City (CityID, CName, StateID) values (25, 'Itaituba', 15);
insert into City (CityID, CName, StateID) values (26, 'Aourir', 6);
insert into City (CityID, CName, StateID) values (27, 'Oslo', 1);
insert into City (CityID, CName, StateID) values (28, 'Radece', 6);
insert into City (CityID, CName, StateID) values (29, 'Mtsensk', 1);
insert into City (CityID, CName, StateID) values (30, 'Mulifanua', 13);
insert into City (CityID, CName, StateID) values (31, 'Ipoh', 13);
insert into City (CityID, CName, StateID) values (32, 'La Rochelle', 1);
insert into City (CityID, CName, StateID) values (33, 'Cikeper', 13);
insert into City (CityID, CName, StateID) values (34, 'Miaoergou', 14);
insert into City (CityID, CName, StateID) values (35, 'Aībak', 5);
insert into City (CityID, CName, StateID) values (36, 'Keerlun', 8);
insert into City (CityID, CName, StateID) values (37, 'Rappang', 9);
insert into City (CityID, CName, StateID) values (38, 'Colonias Unidas', 6);
insert into City (CityID, CName, StateID) values (39, 'Kumba', 5);
insert into City (CityID, CName, StateID) values (40, 'Digne-les-Bains', 2);
insert into City (CityID, CName, StateID) values (41, 'Mikhaylovsk', 4);
insert into City (CityID, CName, StateID) values (42, 'Zulová', 12);
insert into City (CityID, CName, StateID) values (43, 'Mons', 5);
insert into City (CityID, CName, StateID) values (44, 'Sukonolo Krajan', 15);
insert into City (CityID, CName, StateID) values (45, 'Pavlovskaya', 1);
insert into City (CityID, CName, StateID) values (46, 'Los Pinos', 2);
insert into City (CityID, CName, StateID) values (47, 'Jinhu', 9);
insert into City (CityID, CName, StateID) values (48, 'Weston', 14);
insert into City (CityID, CName, StateID) values (49, 'El Rosario', 6);
insert into City (CityID, CName, StateID) values (50, 'Rozhnyativ', 10);
insert into City (CityID, CName, StateID) values (51, 'Tanguá', 4);
insert into City (CityID, CName, StateID) values (52, 'Wanjia', 1);
insert into City (CityID, CName, StateID) values (53, 'Kurungannyawa', 9);
insert into City (CityID, CName, StateID) values (54, 'Taipei', 1);
insert into City (CityID, CName, StateID) values (55, 'Imperatriz', 13);
insert into City (CityID, CName, StateID) values (56, 'Odeshog', 9);
insert into City (CityID, CName, StateID) values (57, 'Orurillo', 14);
insert into City (CityID, CName, StateID) values (58, 'Zhenxi', 6);
insert into City (CityID, CName, StateID) values (59, 'Lisicani', 4);
insert into City (CityID, CName, StateID) values (60, 'Selkirk', 10);
insert into City (CityID, CName, StateID) values (61, 'Envigado', 8);
insert into City (CityID, CName, StateID) values (62, 'Rosario del Ingre', 2);
insert into City (CityID, CName, StateID) values (63, 'Francisco I Madero', 9);
insert into City (CityID, CName, StateID) values (64, 'Buta Ranquil', 12);
insert into City (CityID, CName, StateID) values (65, 'Bonebone', 6);
insert into City (CityID, CName, StateID) values (66, 'Shuitou', 2);
insert into City (CityID, CName, StateID) values (67, 'Zajecov', 8);
insert into City (CityID, CName, StateID) values (68, 'Calvao', 15);
insert into City (CityID, CName, StateID) values (69, 'Cesson', 5);
insert into City (CityID, CName, StateID) values (70, 'Anuchino', 2);
