insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (609, 4, 80, 4, 'amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (391, 2, 100, null, 'gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (417, 2, 64, 0, null);
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (941, 7, 98, 0, 'in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (353, 9, 108, 4, 'lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (53, 8, 84, 1, null);
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (157, 1, 28, null, 'dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (645, 10, 52, 0, 'pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (717, 10, 72, 3, 'volutpat erat quisque erat eros viverra eget congue eget semper');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (717, 11, 72, 3, 'volutpat erat quisque erat eros viverra eget congue eget semper');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (19, 4, 52, 4, 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (433, 8, 4, 0, 'blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (937, 9, 46, 2, 'phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (129, 6, 56, 0, 'sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (359, 3, 48, 4, 'nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (853, 10, 22, null, 'amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (723, 10, 62, 1, null);
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (589, 6, 102, 1, 'tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (633, 9, 42, 0, 'ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (545, 6, 86, 1, 'convallis nunc proin at turpis a pede posuere nonummy integer');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (509, 9, 106, 0, 'turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (953, 5, 72, 2, 'sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (105, 2, 60, 0, null);
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (953, 4, 60, 2, 'sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (151, 10, 44, 4, 'metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (717, 3, 74, 1, 'turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (647, 5, 90, 2, null);
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (67, 2, 40, 0, 'non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (725, 6, 110, 0, null);
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (107, 3, 4, 2, 'ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (717, 2, 12, 0, 'amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (695, 1, 116, 3, null);
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (629, 6, 16, 1, 'duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (681, 7, 74, 3, 'duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (813, 6, 64, 4, null);
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (589, 5, 18, 3, null);
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (569, 3, 106, null, 'elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (119, 8, 108, 2, 'hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (7, 3, 24, 2, 'non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (833, 7, 112, 3, 'morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (429, 1, 58, 2, 'tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (819, 4, 70, 1, 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (977, 1, 68, 1, null);
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (555, 10, 30, 2, 'ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (83, 9, 86, 0, null);
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (285, 3, 72, 0, 'justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (903, 4, 20, 0, 'ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (489, 4, 4, 3, 'libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (875, 6, 4, 1, 'donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (231, 10, 106, null, 'vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (875, 9, 54, 0, 'morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (605, 3, 116, 2, 'nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (1206, 0, 116, 0, 'nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (1206, 1, 16, 0, 'nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (1206, 2, 6, 0, 'nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel');
insert into Report (AdvertisementID, ReportID, UserID, CatID, RDesc) values (1206, 3, 8, 0, 'nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel');